# Generated by Django 6.0.3 on 2026-03-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='options',
            field=models.TextField(blank=True, help_text='Выбранные дополнительные опции', verbose_name='Доп. опции'),
        ),
    ]
