# Generated by Django 6.0.3 on 2026-04-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_page',
            field=models.CharField(blank=True, help_text='Страница, с которой отправлена форма', max_length=255, null=True, verbose_name='Источник'),
        ),
    ]
