# Generated by Django 6.0.3 on 2026-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_source_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='discount_info',
            field=models.TextField(blank=True, help_text='Информация о примененных скидках из калькулятора', verbose_name='Примененные скидки'),
        ),
    ]
