# Generated by Django 6.0.3 on 2026-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Химчистка углового дивана', max_length=150, verbose_name='Заголовок работы')),
                ('image_before', models.ImageField(upload_to='before_after/before/', verbose_name='Фото ДО')),
                ('image_after', models.ImageField(upload_to='before_after/after/', verbose_name='Фото ПОСЛЕ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Работа До/После',
                'verbose_name_plural': 'Работы До/После',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте?')),
            ],
            options={
                'verbose_name': 'Вопрос FAQ',
                'verbose_name_plural': 'FAQ (Вопросы и ответы)',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Для alt-тегов (SEO)', max_length=150, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры (Карусель)',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp', models.URLField(blank=True, verbose_name='Ссылка на WhatsApp')),
                ('telegram', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('seo_title', models.CharField(blank=True, help_text='Например: Химчистка мебели в Алматы | M-Clean', max_length=255, verbose_name='SEO Title Главной')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
