# Generated by Django 6.0.3 on 2026-03-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок для поисковиков (до 60 символов)', max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, help_text='Описание для поисковиков (до 160 символов)', verbose_name='SEO Description')),
                ('og_image', models.ImageField(blank=True, help_text='Изображение для превью в соцсетях', upload_to='seo/og/', verbose_name='OG-изображение')),
                ('icon', models.CharField(choices=[('sofa', 'Диван'), ('carpet', 'Ковёр'), ('mattress', 'Матрас'), ('chair', 'Кресло / Стул'), ('curtain', 'Шторы / Гардины'), ('car', 'Автомобиль')], default='sofa', help_text='Выберите иконку для карточки', max_length=20, verbose_name='Иконка')),
                ('title', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('slug', models.SlugField(help_text='Латиница, без пробелов (например: himchistka-divanov)', max_length=150, unique=True, verbose_name='URL-адрес')),
                ('short_description', models.CharField(help_text='Для карточки на главной (1-2 предложения)', max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, help_text='Для детальной страницы услуги', verbose_name='Полное описание')),
                ('price_from', models.DecimalField(decimal_places=0, default=0, help_text='Базовая цена для отображения', max_digits=10, verbose_name='Цена от (₸)')),
                ('image', models.ImageField(blank=True, help_text='Изображение для карточки', upload_to='services/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры (Карусель)'},
        ),
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, help_text='Ссылка при клике (необязательно)', verbose_name='Сайт партнёра'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_short',
            field=models.TextField(blank=True, help_text="2-3 предложения для блока 'О нас' на главной", verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, help_text='Город, улица', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='M-Clean', max_length=100, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Иконка сайта (PNG, 32x32)', upload_to='branding/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Основной логотип (для хедера)', upload_to='branding/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Белый/светлый логотип для тёмного футера', upload_to='branding/', verbose_name='Логотип для футера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=30, verbose_name='Доп. телефон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Например: Профессиональная химчистка мебели в Алматы', max_length=255, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk',
            field=models.URLField(blank=True, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(blank=True, default='Пн-Вс: 9:00 — 21:00', max_length=100, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='beforeafter',
            name='title',
            field=models.CharField(help_text='Например: Химчистка углового дивана', max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(help_text='Для alt-тегов (SEO)', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Описание для поисковой выдачи (до 160 символов)', verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, verbose_name='WhatsApp'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
