# Generated by Django 6.0.3 on 2026-03-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_alter_partner_options_partner_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Сертификат IICRC, Благодарность от ТОО...', max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение')),
                ('issued_by', models.CharField(blank=True, max_length=200, verbose_name='Кем выдан')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('position', models.CharField(choices=[('manager', 'Менеджер'), ('tech', 'Технолог'), ('master', 'Мастер'), ('driver', 'Водитель'), ('admin', 'Администратор')], default='master', max_length=20, verbose_name='Должность')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, help_text='Стаж работы в компании', verbose_name='Опыт (лет)')),
                ('photo', models.ImageField(blank=True, help_text='Портретное фото', upload_to='team/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, help_text='Краткая биография / интересные факты', max_length=500, verbose_name='О сотруднике')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['order', '-id'],
            },
        ),
    ]
