# Generated by Django 6.0.3 on 2026-03-29 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certificate_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('photo', models.ImageField(blank=True, upload_to='chemicals/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('eco_status', models.CharField(choices=[('eco', 'Экологически безопасно'), ('hypo', 'Гипоаллергенно'), ('safe', 'Безопасно для детей и животных'), ('professional', 'Профессиональное средство')], default='professional', max_length=20, verbose_name='Эко-статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Чистящее средство',
                'verbose_name_plural': 'Чистящие средства',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок акции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка (%)')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Скидка (₸)')),
                ('image', models.ImageField(blank=True, upload_to='discounts/', verbose_name='Изображение')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции и скидки',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('photo', models.ImageField(blank=True, upload_to='equipment/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('features', models.TextField(blank=True, help_text='Каждая характеристика с новой строки', verbose_name='Характеристики')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube видео процесса чистки', verbose_name='YouTube видео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube видео для главной страницы', verbose_name='YouTube видео (главная)'),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('standard', 'Стандарт'), ('premium', 'Премиум')], default='standard', max_length=20, verbose_name='Тариф')),
                ('price', models.DecimalField(decimal_places=0, help_text='Стоимость за единицу', max_digits=10, verbose_name='Цена (₸)')),
                ('unit', models.CharField(default='шт', help_text='шт, м², комплект', max_length=50, verbose_name='Единица измерения')),
                ('features', models.TextField(blank=True, help_text='Каждое преимущество с новой строки', verbose_name='Что входит')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Тариф услуги',
                'verbose_name_plural': 'Тарифы услуг',
                'ordering': ['service', 'tier'],
                'unique_together': {('service', 'tier')},
            },
        ),
    ]
