# Generated by Django 6.0.3 on 2026-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chemical_discount_equipment_service_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например: Лет опыта', max_length=100, verbose_name='Название')),
                ('value', models.PositiveIntegerField(help_text='Число для анимации (8, 10000, 5000)', verbose_name='Значение')),
                ('suffix', models.CharField(blank=True, help_text='+ или тыс.', max_length=10, verbose_name='Суффикс')),
                ('icon', models.CharField(choices=[('calendar', 'Календарь (опыт)'), ('users', 'Люди (клиенты)'), ('sofa', 'Диван (мебель)'), ('ruler', 'Линейка (метры)')], default='calendar', max_length=20, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Факт о компании',
                'verbose_name_plural': 'Факты о компании (счетчики)',
                'ordering': ['order', '-id'],
            },
        ),
    ]
