# Generated by Django 6.0.3 on 2026-03-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sitesettings_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Главное фото справа на первом экране (рекомендуется 600x500)', upload_to='branding/', verbose_name='Фото Hero (справа)'),
        ),
    ]
