# Generated by Django 6.0.3 on 2026-03-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sitesettings_youtube_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Текст под заголовком. Например: Вернём вашей мебели первозданный вид за 2 часа.', verbose_name='Подзаголовок Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.TextField(blank=True, help_text='HTML-разрешён. Например: Профессиональная<br><span>химчистка мебели</span><br>в Алматы', verbose_name='Заголовок Hero (H1)'),
        ),
    ]
