# Generated by Django 6.0.3 on 2026-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_hero_subtitle_sitesettings_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='min_order',
            field=models.DecimalField(decimal_places=0, default=7000, help_text='Минимальная сумма заказа для выезда мастера', max_digits=10, verbose_name='Минимальный заказ (₸)'),
        ),
    ]
