# Generated by Django 6.0.3 on 2026-04-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_min_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='rating_2gis',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Рейтинг 2ГИС'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rating_google',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Рейтинг Google'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rating_yandex',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Рейтинг Яндекс'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='url_reviews_2gis',
            field=models.URLField(blank=True, verbose_name='Ссылка на отзывы 2ГИС'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='url_reviews_google',
            field=models.URLField(blank=True, verbose_name='Ссылка на отзывы Google'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='url_reviews_yandex',
            field=models.URLField(blank=True, verbose_name='Ссылка на отзывы Яндекс'),
        ),
    ]
