# Generated by Django 6.0.3 on 2026-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_rating_2gis_sitesettings_rating_google_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Только цифры, например 77075288004', max_length=20, verbose_name='Номер WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='Полная ссылка, например https://wa.me/...', verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
