# Generated by Django 6.0.3 on 2026-04-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_whatsapp_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='whatsapp',
        ),
    ]
