# Generated by Django 6.0.3 on 2026-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_sitesettings_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='watermark',
            field=models.ImageField(blank=True, help_text='PNG с прозрачностью для наложения на фото портфолио', null=True, upload_to='settings/', verbose_name='Водяной знак'),
        ),
    ]
