# Generated by Django 6.0.3 on 2026-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('cert', 'Сертификат'), ('gratitude', 'Благодарственное письмо')], default='cert', max_length=20, verbose_name='Категория'),
        ),
    ]
