# Generated by Django 6.0.3 on 2026-04-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_certificate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст изображения'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст фото'),
        ),
        migrations.AddField(
            model_name='discount',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст изображения'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст фото'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст логотипа'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст фото'),
        ),
    ]
