# Generated by Django 6.0.3 on 2026-04-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_certificate_image_alt_chemical_photo_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('shield', 'Щит (Гарантия)'), ('clock', 'Часы (Время)'), ('truck', 'Машина (Выезд)'), ('credit-card', 'Карта (Оплата)'), ('star', 'Звезда (Качество)'), ('check-circle', 'Галочка')], default='check-circle', max_length=20, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировано')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Почему выбирают нас (Преимущества)',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('phone', 'Телефон (Заявка)'), ('calculator', 'Калькулятор (Расчет)'), ('calendar', 'Календарь (Время)'), ('truck', 'Машина (Выезд)'), ('sparkles', 'Звезды (Работа)'), ('check-circle', 'Галочка (Сдача)')], default='check-circle', max_length=20, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировано')),
            ],
            options={
                'verbose_name': 'Шаг работы',
                'verbose_name_plural': 'Как мы работаем (Шаги)',
                'ordering': ['order', '-id'],
            },
        ),
    ]
