# Generated by Django 6.0.3 on 2026-04-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_advantage_workstep'),
        ('services', '0017_service_seo_description_service_seo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='services',
            field=models.ManyToManyField(blank=True, help_text="Оставьте пустым — вопрос будет 'общим' (покажется на страницах без своих вопросов)", related_name='faqs', to='services.service', verbose_name='Услуги (привязка)'),
        ),
    ]
