# Generated by Django 6.0.3 on 2026-04-12 17:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_faq_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок для поисковиков (до 60 символов)', max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, help_text='Описание для поисковиков (до 160 символов)', verbose_name='SEO Description')),
                ('og_image', models.ImageField(blank=True, help_text='Изображение для превью в соцсетях', upload_to='seo/og/', verbose_name='OG-изображение')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(help_text='Например: policy, terms, notice', max_length=150, unique=True, verbose_name='URL-слаг')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Основной текст страницы.', verbose_name='Контент (Текст)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Инфо-страница (Юридическая)',
                'verbose_name_plural': 'Инфо-страницы',
                'ordering': ['order', 'title'],
            },
        ),
    ]
