# Generated by Django 6.0.3 on 2026-04-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_legalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='show_on_main',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
