# Generated by Django 6.0.3 on 2026-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_faq_show_on_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_text',
            field=models.CharField(default='Работаем с 2015 года', help_text='Текст в маленькой плашке над заголовком', max_length=100, verbose_name='Текст бейджа Hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Иконка сайта (PNG, SVG, ICO)', upload_to='branding/', verbose_name='Favicon'),
        ),
    ]
