# Generated by Django 6.0.3 on 2026-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitesettings_hero_badge_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_badge_text',
            field=models.CharField(default='Работаем с 2015 года', help_text="Текст в маленькой плашке над заголовком. Если оставить пустым, будет 'Работаем X лет'.", max_length=100, verbose_name='Текст бейджа Hero'),
        ),
    ]
