# Generated by Django 6.0.3 on 2026-03-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL-адрес')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('sofa', 'Диван'), ('carpet', 'Ковёр'), ('mattress', 'Матрас'), ('chair', 'Кресло / Стул'), ('curtain', 'Шторы / Гардины'), ('car', 'Автомобиль')], default='sofa', max_length=20, verbose_name='Иконка')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Базовая цена (₸)')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена (₸)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('services', models.ManyToManyField(blank=True, related_name='options', to='services.service', verbose_name='Доступна для услуг')),
            ],
            options={
                'verbose_name': 'Доп. опция',
                'verbose_name_plural': 'Доп. опции (калькулятор)',
                'ordering': ['order', '-id'],
            },
        ),
    ]
