# Generated by Django 6.0.3 on 2026-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='premium_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Включает экстрактор Santoemma, химию Chemspec USA, удаление запаха', max_digits=10, verbose_name='Премиум цена (₸)'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(default='шт', help_text='Например: шт, м², комплект', max_length=30, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, help_text='Видео процесса чистки (вставьте ссылку)', verbose_name='Ссылка на YouTube'),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Обычная чистка', max_digits=10, verbose_name='Стандарт цена (₸)'),
        ),
    ]
