# Generated by Django 6.0.3 on 2026-03-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_premium_price_service_unit_service_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='video_url',
        ),
        migrations.AddField(
            model_name='service',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Только ID видео, например: dQw4w9WgXcQ', max_length=20, verbose_name='YouTube видео ID'),
        ),
    ]
