# Generated by Django 6.0.3 on 2026-03-30 10:02

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_video_url_service_youtube_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='youtube_video_id',
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Вставьте полную ссылку на YouTube видео', null=True, verbose_name='Видео (YouTube)'),
        ),
    ]
