# Generated by Django 6.0.3 on 2026-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_youtube_video_id_service_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtainCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип ткани')),
                ('coefficient', models.DecimalField(decimal_places=2, default=0.6, help_text='Сколько кг весит 1 м² ткани', max_digits=5, verbose_name='Коэффициент веса (кг/м²)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Коэффициент штор',
                'verbose_name_plural': 'Коэффициенты штор',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='additionaloption',
            name='impact_type',
            field=models.CharField(choices=[('total', 'От итоговой суммы'), ('base', 'От базовой цены')], default='total', help_text='От чего считается процент: от итога или от базы', max_length=10, verbose_name='Тип расчёта скидки/наценки'),
        ),
        migrations.AddField(
            model_name='additionaloption',
            name='is_percentage',
            field=models.BooleanField(default=False, help_text='Если да — цена будет считаться как процент от суммы', verbose_name='Считать в процентах?'),
        ),
        migrations.AddField(
            model_name='service',
            name='calc_type',
            field=models.CharField(choices=[('default', 'Стандартный (поштучно)'), ('carpet', 'Ковролин (по м²)'), ('curtains', 'Шторы (по весу/окнам)')], default='default', help_text='Выберите тип расчёта для этой услуги', max_length=20, verbose_name='Тип калькулятора'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Фиксированная цена или процент (если включён процент)', max_digits=10, verbose_name='Цена (₸)'),
        ),
    ]
