# Generated by Django 6.0.3 on 2026-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_curtaincoefficient_additionaloption_impact_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaloption',
            name='impact_type',
        ),
        migrations.RemoveField(
            model_name='additionaloption',
            name='is_percentage',
        ),
        migrations.AddField(
            model_name='additionaloption',
            name='calc_unit',
            field=models.CharField(choices=[('fixed', 'Фиксированная цена'), ('per_kg', 'За кг'), ('per_m2', 'За м²'), ('per_item', 'За штуку'), ('percentage', 'Процент от суммы')], default='fixed', help_text='Как считается: фиксировано, за кг, за м², за штуку или процент', max_length=20, verbose_name='Единица расчёта'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_rules',
            field=models.JSONField(blank=True, help_text='Для ковролина: {"tiers": [{"max_area": 25, "price": 2000}, {"max_area": 50, "price": 1750}]}. Оставьте пустым для обычной цены.', null=True, verbose_name='Правила цен (JSON)'),
        ),
        migrations.AlterField(
            model_name='additionaloption',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Фиксированная цена, цена за единицу или процент', max_digits=10, verbose_name='Цена (₸ или %)'),
        ),
    ]
