# Generated by Django 6.0.3 on 2026-04-03 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_additionaloption_impact_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_rules',
        ),
        migrations.CreateModel(
            name='ServiceTierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_area', models.PositiveIntegerField(help_text='Максимальная площадь для этого тарифа. Например: 25', verbose_name='До скольки м²')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена за м² (₸)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Ступень цены',
                'verbose_name_plural': 'Ступени цен',
                'ordering': ['max_area'],
            },
        ),
    ]
