# Generated by Django 6.0.3 on 2026-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_price_rules_servicetierprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaloption',
            name='price_rules',
            field=models.JSONField(blank=True, help_text='Для ступенчатых цен: {"tiers": [{"max_value": 150, "price": 20}, {"max_value": 300, "price": 10}]}. Оставьте пустым для обычной цены.', null=True, verbose_name='Правила цен (ступенчатые)'),
        ),
    ]
