# Generated by Django 6.0.3 on 2026-04-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_additionaloption_price_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaloption',
            name='price_rules',
        ),
    ]
