# Generated by Django 6.0.3 on 2026-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_additionaloption_price_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaloption',
            name='show_in_carpet',
            field=models.BooleanField(default=True, verbose_name='В калькуляторе Ковролина'),
        ),
        migrations.AddField(
            model_name='additionaloption',
            name='show_in_curtains',
            field=models.BooleanField(default=True, verbose_name='В калькуляторе Штор'),
        ),
        migrations.AddField(
            model_name='additionaloption',
            name='show_in_furniture',
            field=models.BooleanField(default=True, verbose_name='В калькуляторе Мебели'),
        ),
    ]
