# Generated by Django 6.0.3 on 2026-04-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_additionaloption_show_in_carpet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='premium_price',
        ),
    ]
