# Generated by Django 6.0.3 on 2026-04-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_service_premium_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_client_type',
            field=models.CharField(choices=[('home', 'Физлица (Дом)'), ('business', 'Бизнес (Офис)')], default='home', help_text='Для калькулятора мебели', max_length=10, verbose_name='Тип клиента по умолчанию'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_material',
            field=models.CharField(choices=[('fabric', 'Ткань'), ('leather', 'Кожа')], default='fabric', help_text='Для калькулятора мебели', max_length=10, verbose_name='Материал по умолчанию'),
        ),
        migrations.AlterField(
            model_name='service',
            name='calc_type',
            field=models.CharField(choices=[('default', 'Стандартный (поштучно)'), ('furniture', 'Мебель (диваны/кресла)'), ('carpet', 'Ковролин (по м²)'), ('curtains', 'Шторы (по весу/окнам)')], default='default', help_text='Выберите тип расчёта для этой услуги', max_length=20, verbose_name='Тип калькулятора'),
        ),
    ]
