# Generated by Django 6.0.3 on 2026-04-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_default_client_type_service_default_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Для превью и карточек (1-2 предложения)', verbose_name='Краткое описание'),
        ),
    ]
