# Generated by Django 6.0.3 on 2026-04-10 16:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_service_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Для SEO', max_length=255, verbose_name='Alt-текст фото'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Блок 'Как мы работаем' (Можно с фото и видео)", verbose_name='Процесс работы (HTML)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
    ]
