# Generated by Django 6.0.3 on 2026-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_service_image_alt_service_process_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtaincoefficient',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Оставьте пустым чтобы использовать базовую цену услуги. Заполните для переопределения цены для данного типа ткани.', max_digits=10, null=True, verbose_name='Цена за кг (₸)'),
        ),
    ]
