# Generated by Django 6.0.3 on 2026-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_add_curtain_price_per_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='process_description',
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Обычная чистка', max_digits=10, verbose_name='Базовая цена (от)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Для карточек и превью (1-2 предложения)', verbose_name='Краткое описание'),
        ),
    ]
