# Generated by Django 6.0.3 on 2026-04-10 20:34

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_service_process_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Если пусто, используется краткое описание', verbose_name='SEO Описание (Meta Description)'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если пусто, используется название услуги', max_length=255, verbose_name='SEO Заголовок (Meta Title)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Вставьте полную ссылкy на YouTube видео', null=True, verbose_name='Видео (YouTube)'),
        ),
    ]
