# Generated by Django 6.0.3 on 2026-04-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_workcase_image_after_alt_workcase_image_before_alt_and_more'),
        ('services', '0017_service_seo_description_service_seo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured_works',
            field=models.ManyToManyField(blank=True, help_text="Выберите работы, которые будут показаны в блоке 'Наши работы' на странице услуги. Если пусто — показываются работы из той же категории", related_name='featured_in_services', to='portfolio.workcase', verbose_name='Избранные работы (портфолио)'),
        ),
    ]
