# Generated by Django 6.0.3 on 2026-03-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL-адрес')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL-адрес')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Изображение')),
                ('excerpt', models.TextField(help_text='Для превью в списке статей', max_length=500, verbose_name='Краткое описание')),
                ('content', models.TextField(help_text='Основной контент. Поддерживается HTML.', verbose_name='Текст статьи (HTML)')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('seo_title', models.CharField(blank=True, help_text='Заголовок для поисковиков', max_length=255, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, help_text='Описание для поисковой выдачи', verbose_name='SEO Description')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Блог (Статьи)',
                'ordering': ['-published_at'],
            },
        ),
    ]
