# Generated by Django 6.0.3 on 2026-04-10 16:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_post_author_post_faqs_post_views_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Для SEO. Например: Чистка дивана в Алматы', max_length=255, verbose_name='Alt-текст изображения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Основной контент. Поддерживается HTML и медиа.', verbose_name='Текст статьи'),
        ),
    ]
