# Generated by Django 6.0.3 on 2026-03-28 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('source', models.CharField(choices=[('yandex', 'Яндекс'), ('2gis', '2ГИС'), ('google', 'Google'), ('own', 'Свой сайт')], default='yandex', max_length=20, verbose_name='Источник')),
                ('date', models.DateField(verbose_name='Дата отзыва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_before', models.ImageField(upload_to='portfolio/before/', verbose_name='Фото ДО')),
                ('image_after', models.ImageField(upload_to='portfolio/after/', verbose_name='Фото ПОСЛЕ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Работа (До/После)',
                'verbose_name_plural': 'Портфолио (До/После)',
                'ordering': ['order', '-id'],
            },
        ),
    ]
