# Generated by Django 6.0.3 on 2026-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено к показу'),
        ),
        migrations.AddField(
            model_name='review',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал отзыва'),
        ),
    ]
