# Generated by Django 6.0.3 on 2026-04-06 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_review_is_approved_review_source_url'),
        ('services', '0011_remove_service_premium_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_cases', to='services.category', verbose_name='Категория'),
        ),
    ]
