# Generated by Django 6.0.3 on 2026-04-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_certificate_image_alt_chemical_photo_alt_and_more'),
        ('portfolio', '0003_workcase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcase',
            name='image_after_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст фото ПОСЛЕ'),
        ),
        migrations.AddField(
            model_name='workcase',
            name='image_before_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст фото ДО'),
        ),
        migrations.AddField(
            model_name='workcase',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_cases', to='core.partner', verbose_name='Партнёр / Клиент'),
        ),
    ]
