# Generated by Django 6.0.3 on 2026-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_workcase_image_after_alt_workcase_image_before_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcase',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной?'),
        ),
    ]
